import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/next";
import { Cormorant_Garamond, Montserrat, Parisienne } from "next/font/google";
import { Header } from "@/components/Header/Header";
import "./styles/globals.css";
import { Footer } from "@/components/Footer/Footer";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap",
});

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-cormorant",
  display: "swap",
});

const parisienne = Parisienne({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-parisienne",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html
      lang={locale}
      className={`light ${montserrat.variable} ${cormorant.variable} ${parisienne.variable}`}
    >
      <body className="antialiased bg-background font-sans">
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Header />
          {children}
          {process.env.NODE_ENV === "production" && <Analytics />}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
